<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGcggZxh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGcggZxh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGcggZxh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGcggZxh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGcggZxh\App_KernelDevDebugContainer([
    'container.build_hash' => 'GcggZxh',
    'container.build_id' => '01987a2e',
    'container.build_time' => 1667688635,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGcggZxh');
