<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.188fa053.js',
                '/build/488.ee17fc27.js',
                '/build/app.e541c0ce.js',
            ],
            'css' => [
                '/build/488.f343a2d0.css',
                '/build/app.bc1f5694.css',
            ],
        ],
    ],
],

]];
